IIoW/IIslander

src/modules/automod/message.js

fix: automodOnSpecificServer

---

package.json
yarn.lock

Wilson's patch was merged 5 days ago, see [this](https://github.com/eslachance/enmap/commit/feffa960f705ec1294bb200e695b92da96321290).

chore(deps): change enmap source repo

---

src/modules/messagePreview/module.js

feat: link preview permissions

---

.github/CODEOWNERS
src/constants/Blacklist.js
src/constants/Messages.js
src/dto/ResponseDto.js
src/dto/UserDto.js
src/helper/index.js
src/helper/main.js
src/modUtil.js
src/modules/automod/message.js
src/modules/leveling/awards/reactions.js
src/modules/modCommands/commands/autoresponse.js
src/modules/modCommands/commands/move.js
src/util.js
src/xpHandling.js

Features:
Added firebase import to helper.
Fixes/Changes:
Added myself to codeowners for helper.
Added a getAndAddRole util which gets a role and adds it.
Added countEmbed to util.
Made adding xp ensure xp is round.
Improved blacklist.
Update swear warning 0.
Removed ununsed value isRegex from ResponceDto.
Remove unused value key from userDto.
Added eligibleGiveaways to userDto. Right not it just so we don't lose data on import.
Made helper keep existing node options (allowing vscode's debugger to work).
Fix swearing not updating if penalized.
Auto responce ls doesn't crash as much.

feat: firebase import & misc

---

yarn.lock

It should speedup docker builds

chore(deps): update better-sqlite3 & regenerate lockfile

---

src/dto/KeyDto.js
src/helper/main.js
src/modules/dmCommands/commands/steamRequest.js
src/modules/interactions/buttons/giveaway.js
src/util.js

Store keys.
Firebase import now imports keys.
Allow users to redeem keys if they won a giveaway.
Closes #58

feat: giveaways

---

.env.example
src/dto/UserDto.js
src/helper/main.js
src/modules/dmCommands/commands/steamRequest.js
src/modules/interactions/buttons/giveaway.js
src/roles.js

Added giveaway roles to db.
Store giveaway roles as nums.
Import giveaway roles as nums.
Figure out old giveaway roles (cause they were not stored previously)

feat: giveaway role managment

---

src/constants/OffenseDescriptions.js
src/modules/automod/message.js
src/modules/cooldownNotifications/module.js
src/modules/modCommands/commands/autoresponse.js
src/modules/modCommands/commands/move.js
src/modules/modCommands/commands/nickname.js
src/modules/modCommands/commands/purge.js
src/modules/welcome/module.js
src/util.js

This PR fixes a bunch of misc issues found when testing.

fix: misc stuff

---

.env.example
src/config.js
src/dto/UserDto.js
src/helper/main.js
src/modules/dmCommands/commands/steamRequest.js
src/roles.js

Rewrite giveaways in a structure that works with the new roles.

chore: rewrite giveaways

---

src/constants/Awards.js
src/modules/leveling/awards/reactions.js
src/permissions.js

Awards now check if you can give that award. (oops)
Donor xp is now passed a member so their name shows up.

fix: award stuff

---

src/modules/welcome/module.js

Let me know if you find anything else

fix: broken welcome check

---

src/modules/automod/message.js

some more replacements for automod

fix: more replacements

---

src/modules/autoresponses/textResponses.js

:/ forgot that triggers consisting of two words exists

fix: autoresponse triggers again

---

src/modules/dmCommands/commands/levelping.js
src/notifications.js

added command for the user to decide whether to get pings on level ups or not
closes #149

feat: levelping command

---

src/modules/leveling/voice/voice.js

Added a limit to voice xp of 3 hours of whatever one is doing. 
this avoids afk problems.

feat: voice xp limit

---

src/modules/leveling/awards/reactions.js
src/modules/leveling/awards/starboard.js

Causes starboard to work again.
Can be reverted when patched upstream.

fix: workaround reaction.me

---

src/modules/leveling/awards/reactions.js

bot messages will no longer be able to be awarded

fix: bot messages being pushed to starboard

---

src/modules/welcome/module.js

Noticed that markdown on usernames affected the welcome messages in #just-chatting

fix: sanitize username

---

src/constants/Blacklist.js
src/modules/automod/message.js

Opionated changes to the wordlist and modified functionality for less strict automod.

feat: automod changes

---

.github/workflows/build.yml
.github/workflows/codeql.yml
.github/workflows/format.yml

chore(ci): update actions

---

src/constants/Blacklist.js

ya all need to code review better, makes this entire process useless
whomever approves last pls merge

fix: update swearwords

---

src/modules/welcome/module.js

only send welcome messages after member is done screening

feat: screening

---

.eslintrc.json
package.json
src/constants/Blacklist.js
src/dto/EmbedPage.js
src/dto/EmbedPageMessage.js
src/index.js
src/modUtil.js
src/modules/automod/message.js
src/modules/autoresponses/textResponses.js
src/modules/dmCommands/commands/factions.js
src/modules/dmCommands/commands/help.js
src/modules/dmCommands/commands/settings.js
src/modules/dmCommands/commands/spoilores.js
src/modules/dmCommands/commands/steamOwner.js
src/modules/dmCommands/commands/steamRequest.js
src/modules/errorHandling/module.js
src/modules/interactions/buttons/factions.js
src/modules/interactions/buttons/giveaway.js
src/modules/interactions/buttons/settings.js
src/modules/leveling/awards/starboard.js
src/modules/messagePreview/module.js
src/modules/modCommands/commands/autoresponse.js
src/modules/modCommands/commands/help.js
src/modules/modCommands/commands/move.js
src/modules/modCommands/commands/offences.js
src/roles.js
src/util.js
yarn.lock

It's not erroring, but everything needs to be tested still.

feat: d.js v14
